# COGS 118B Final Project - FIFA

## Team Name: Hong Shao Rou

- Sue Xia
- Yu Pan
- Weichong Ling
- Huiran Song
- Danrui Wang

## Library Import

In [2]:
import numpy as np 
import pandas as pd

## Data Clean

In [3]:
#Read the data
df = pd.read_csv('players_20.csv')

In [4]:
#rough data overview
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [5]:
#summary statistics
print(df.shape)
df.describe()

(18278, 104)

,sofifa_id,age,height_cm,weight_kg,overall,potential,value_eur,wage_eur,international_reputation,weak_foot,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
count,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,1.827800e+04,18278.000000,18278.000000,18278.000000,...,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000
mean,219738.864482,25.283291,181.362184,75.276343,66.244994,71.546887,2.484038e+06,9456.942773,1.103184,2.944250,...,48.383357,58.528778,46.848889,47.640333,45.606631,16.572765,16.354853,16.212934,16.368038,16.709924
std,27960.200461,4.656964,6.756961,7.047744,6.949953,6.139669,5.585481e+06,21351.714095,0.378861,0.664656,...,15.708099,11.880840,20.091287,21.585641,21.217734,17.738069,16.996925,16.613665,17.136497,18.038125
min,768.000000,16.000000,156.000000,50.000000,48.000000,49.000000,0.000000e+00,0.000000,1.000000,1.000000,...,7.000000,12.000000,1.000000,5.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,204445.500000,22.000000,177.000000,70.000000,62.000000,67.000000,3.250000e+05,1000.000000,1.000000,3.000000,...,39.000000,51.000000,29.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,226165.000000,25.000000,181.000000,75.000000,66.000000,71.000000,7.000000e+05,3000.000000,1.000000,3.000000,...,49.000000,60.000000,52.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,240795.750000,29.000000,186.000000,80.000000,71.000000,75.000000,2.100000e+06,8000.000000,1.000000,3.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,252905.000000,42.000000,205.000000,110.000000,94.000000,95.000000,1.055000e+08,565000.000000,5.000000,5.000000,...,92.000000,96.000000,94.000000,92.000000,90.000000,90.000000,92.000000,93.000000,91.000000,92.000000

In [6]:
#drop the columns with no value
df_any = df.dropna(axis='columns')
df_any.shape

(18278, 56)

In [7]:
# Drop columns in which more than 10% of values are missing:
df_10 = df.dropna(thresh=len(df)*0.9, axis='columns')
df_10.shape

(18278, 61)

In [8]:
# determine which columns have missing data
df_10.isna().any()

sofifa_id                  False
player_url                 False
short_name                 False
long_name                  False
age                        False
                           ...
goalkeeping_diving         False
goalkeeping_handling       False
goalkeeping_kicking        False
goalkeeping_positioning    False
goalkeeping_reflexes       False
Length: 61, dtype: bool

In [9]:
# how many missing values in df_10
df_10.isna().sum().sum()

3306

I made 2 dataframes: 
- df_any dropped all columns with missing values
- df_10 dropped the columns have more than 10% missing values.

I suggest to use df_any, but you could use df_10 if you want.

In [10]:
# Check columns
df_any.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club', 'overall', 'potential',
       'value_eur', 'wage_eur', 'player_positions', 'preferred_foot',
       'international_reputation', 'weak_foot', 'skill_moves', 'work_rate',
       'body_type', 'real_face', 'attacking_crossing', 'attacking_finishing',
       'attacking_heading_accuracy', 'attacking_short_passing',
       'attacking_volleys', 'skill_dribbling', 'skill_curve',
       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',
       'movement_acceleration', 'movement_sprint_speed', 'movement_agility',
       'movement_reactions', 'movement_balance', 'power_shot_power',
       'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots',
       'mentality_aggression', 'mentality_interceptions',
       'mentality_positioning', 'mentality_vision', 'mentality_penalties',
       'mentality_composure', 'defending_marking', 'defending_standing_tackle',
       'defending_sliding_tackle', 'goalkeeping_diving',
       'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes'],
      dtype='object')

In [11]:
##############

In [12]:
df_numeric = df.select_dtypes(include=[np.number])
temp = df['player_positions']
df_numeric['positions'] = temp
df_numeric

<ipython-input-12-ccfead3bc93e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_numeric['positions'] = temp

,sofifa_id,age,height_cm,weight_kg,overall,potential,value_eur,wage_eur,international_reputation,weak_foot,...,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,positions
0,158023,32,170,72,94,94,95500000,565000,5,4,...,96,33,37,26,6,11,15,14,8,"RW, CF, ST"
1,20801,34,187,83,93,93,58500000,405000,5,4,...,95,28,32,24,7,11,15,14,11,"ST, LW"
2,190871,27,175,68,92,92,105500000,290000,5,5,...,94,27,26,29,9,9,15,15,11,"LW, CAM"
3,200389,26,188,87,91,93,77500000,125000,3,3,...,68,27,12,18,87,92,78,90,89,GK
4,183277,28,175,74,91,91,90000000,470000,4,4,...,91,34,27,22,11,12,6,8,8,"LW, CF"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,22,186,79,48,56,40000,2000,1,3,...,41,45,50,52,5,5,13,5,14,CB
18274,250995,22,177,66,48,56,40000,2000,1,2,...,35,42,53,57,13,6,14,11,9,CB
18275,252332,19,186,75,48,56,40000,1000,1,2,...,39,46,52,46,7,8,10,6,14,CM
18276,251110,18,185,74,48,54,40000,1000,1,2,...,40,39,44,54,14,9,13,13,13,CM
18277,233449,26,182,78,48,51,40000,2000,1,3,...,42,52,42,48,8,12,14,9,10,CM

In [13]:
df_numeric = df_numeric.drop(['sofifa_id','value_eur', 'wage_eur', 'international_reputation','release_clause_eur', 'team_jersey_number',
       'contract_valid_until', 'nation_jersey_number','gk_diving','gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed',
       'gk_positioning'],axis=1)

In [14]:
df_numeric.isna().sum()

age                              0
height_cm                        0
weight_kg                        0
overall                          0
potential                        0
weak_foot                        0
skill_moves                      0
pace                          2036
shooting                      2036
passing                       2036
dribbling                     2036
defending                     2036
physic                        2036
attacking_crossing               0
attacking_finishing              0
attacking_heading_accuracy       0
attacking_short_passing          0
attacking_volleys                0
skill_dribbling                  0
skill_curve                      0
skill_fk_accuracy                0
skill_long_passing               0
skill_ball_control               0
movement_acceleration            0
movement_sprint_speed            0
movement_agility                 0
movement_reactions               0
movement_balance                 0
power_shot_power                 0
power_jumping                    0
power_stamina                    0
power_strength                   0
power_long_shots                 0
mentality_aggression             0
mentality_interceptions          0
mentality_positioning            0
mentality_vision                 0
mentality_penalties              0
mentality_composure              0
defending_marking                0
defending_standing_tackle        0
defending_sliding_tackle         0
goalkeeping_diving               0
goalkeeping_handling             0
goalkeeping_kicking              0
goalkeeping_positioning          0
goalkeeping_reflexes             0
positions                        0
dtype: int64

In [15]:
df_numeric = df_numeric.dropna()

In [16]:
df_pos = df_numeric['positions']
df_numeric = df_numeric.drop(['positions'],axis = 1)

In [17]:
print(df_numeric.shape)
print(df_pos.shape)

(16242, 47)
(16242,)

In [18]:
df_numeric.head(10)

,age,height_cm,weight_kg,overall,potential,weak_foot,skill_moves,pace,shooting,passing,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
0,32,170,72,94,94,4,4,87.0,92.0,92.0,...,75,96,33,37,26,6,11,15,14,8
1,34,187,83,93,93,4,5,90.0,93.0,82.0,...,85,95,28,32,24,7,11,15,14,11
2,27,175,68,92,92,5,5,91.0,85.0,87.0,...,90,94,27,26,29,9,9,15,15,11
4,28,175,74,91,91,4,4,91.0,83.0,86.0,...,88,91,34,27,22,11,12,6,8,8
5,28,181,70,91,91,5,4,76.0,86.0,92.0,...,79,91,68,58,51,15,13,5,10,13
7,27,193,92,90,91,3,2,77.0,60.0,70.0,...,62,89,91,92,85,13,10,13,11,11
8,33,172,66,90,90,4,4,74.0,76.0,89.0,...,82,92,68,76,71,13,9,7,14,9
9,27,175,71,90,90,3,4,93.0,86.0,81.0,...,77,91,38,43,41,14,14,9,11,14
10,20,178,73,89,95,4,5,96.0,84.0,78.0,...,70,84,34,34,32,13,5,7,11,6
11,28,187,89,89,91,3,2,71.0,28.0,54.0,...,33,82,91,90,87,7,11,7,13,5

## Data Exploration and Analysis

## K-means

## Spectral Clustering

## Mixture of Gaussian (MOG)

In [19]:
df_numeric.head()

,age,height_cm,weight_kg,overall,potential,weak_foot,skill_moves,pace,shooting,passing,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
0,32,170,72,94,94,4,4,87.0,92.0,92.0,...,75,96,33,37,26,6,11,15,14,8
1,34,187,83,93,93,4,5,90.0,93.0,82.0,...,85,95,28,32,24,7,11,15,14,11
2,27,175,68,92,92,5,5,91.0,85.0,87.0,...,90,94,27,26,29,9,9,15,15,11
4,28,175,74,91,91,4,4,91.0,83.0,86.0,...,88,91,34,27,22,11,12,6,8,8
5,28,181,70,91,91,5,4,76.0,86.0,92.0,...,79,91,68,58,51,15,13,5,10,13

In [36]:
from sklearn.preprocessing import StandardScaler

val = df_numeric.values
scaler = StandardScaler()
scaler.fit(val)
data = scaler.transform(val)
data.shape

(16242, 47)

In [37]:
# Initialization k = 11
from scipy.stats import multivariate_normal

np.random.seed(42)
u = np.random.rand(11,47)
sigma = np.identity(47)
pi = np.random.rand(11)

In [41]:
# E-Step
# Return matrix gamma N*K (18278, 11)
def GMM_E(u,sigma,pi):

(53, 53)

In [39]:
for i in range(11):
    print(multivariate_normal.pdf(data[0], mean=u[i], cov=sigma))

4.633102570247006e-62
8.025431098154061e-59
3.459346205958252e-58
2.77460542843882e-60
4.949849179154936e-58
1.443677655781837e-54
4.8973351505787e-60
1.2378044062568617e-58
2.0373617475086616e-53
5.059975637188537e-59
2.3977528627397065e-58